version: '3'
services:
  web-app:
    image: my-school-web-app
    ports:
      - 8091:8091
    repeat: always
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'school_db'
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3307:3306
    repeat: always
    volume:
      - school_db:/var/lib/mysql
volumes:
  school_db:
