version: "3"
services:
  web-app:
    image: my-school-web-app
    ports:
      - 8089:8089
    restart: always
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "school_db"
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3307:3306
    restart: always
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
